

name: Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v2

      
      - name: install dependencies
        run: npm install
      - name: Build live2d_bundle.js
        run: npm run build:prod
      - name: Push to Github
        run: |
          git config --global user.name "DomathID"
          git config --global user.email "bangdompret@gmail.com"
          git add dist
          git commit -m "Auto built from ${{ github.sha }}"
          git push
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
